# Generated by Django 6.0.6 on 2026-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
