# Generated by Django 6.0.6 on 2026-07-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classe_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
    ]
