# Generated by Django 6.0.6 on 2026-07-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_classe_annee_scolaire_remove_classe_niveau_and_more'),
        ('teachers', '0002_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='annee_scolaire',
            field=models.CharField(default='2025-2026', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
